- title: Founder's Corner
  description: Build your own online business and make money online in this 12-week startup program (FI only).
  link_label: More information
  link_url: https://link.webropolsurveys.com/EP/F7BF2C2ED5A0FB24
  stage: just-exploring, getting-started
- title: Startup Express
  description: Turn your idea into a startup in 100 days with help of a community.
  link_label: More information
  link_url: https://oulu.com/en/startup-express-pre-incubator/
  stage: just-exploring, getting-started
- title: Uusyrityskeskus
  description: Helps you evaluate your business idea from various perspectives and start your company.
  link_label: More information
  link_url: https://www.oulunseudunuusyrityskeskus.fi/en/home/
  stage: getting-started, ready-to-grow
- title: OYSTER Incubator
  description: Supports building new innovations in digital health, health technology, the health and well-being industry, and diagnostics
  link_label: More information
  link_url: https://ouluhealth.fi/oyster/
  stage: just-exploring, getting-started, ready-to-grow
- title: AI-Incubator
  description: A 9-month, cohort-based program that helps early-stage AI founders validate their ideas, build solutions, and work toward their first customer with structured support, mentorship and ecosystem connections.
  link_label: More information
  link_url: https://www.startupoulu.com/ai-incubator/
  stage: getting-started, ready-to-grow
- title: Startup Station
  description: Offers inspiration, knowledge and support though experts, events and training programs.
  link_label: More information
  link_url: https://oulu.com/en/startup-station/
  stage: just-exploring, getting-started
- title: Kielo Growth
  description: Support the building of startups by offering office spaces, angel investor funding and a strong community.
  link_label: More information
  link_url: https://kielo.com/
  stage: ready-to-grow
- title: OuluES
  description: Promotes entrepreneurial student community and culture in Oulu.
  link_label: More information
  link_url: https://www.oulues.com
  stage: just-exploring, getting-started
- title: BusinessOulu Funding Services
  description: BusinessOulu helps clarify your financing needs and funding options related to the start-up, development, growth and internationalization of the company.
  link_label: More information
  link_url: https://www.businessoulu.com/en/businesses-and-entrepreneurs/business-development/financial-advice/
  stage: getting-started, ready-to-grow
- title: OuluHealth Labs
  description: Co-creation platform for social and healthcare professionals, citizens, companies, and other stakeholders (e.g., third sector)
  link_label: More information
  link_url: https://ouluhealth.fi/services/ouluhealth-labs/
  stage: getting-started, ready-to-grow
- title: Printocent
  description: Pilot plant for the production of new product concepts and prototypes.
  link_label: More information
  link_url: https://www.printocent.net/
  stage: getting-started, ready-to-grow
- title: University Innovation Centre
  description: Offers support for research commercialization and funding for new innovations. 
  link_label: More information
  link_url: https://www.oulu.fi/en/cooperation/innovation-and-entrepreneurship
  stage: just-exploring, getting-started, ready-to-grow
- title: Business Corner
  description: Entrepreneurial hub in Linnanmaa campus, where we build founders and startups through mentoring, different programs and our member community. Walk-in startup mentoring available every Wednesday morning. 
  link_label: More information
  link_url: https://oamk.fi/en/development-platforms/business-corner/
  stage: just-exploring, getting-started, ready-to-grow
- title: Oulu Game Industry Pre-Incubator
  description: Are you interested in making games? Do you perhaps dream of making games as a living someday? Come learn how it’s done in Oulu Game Industry Pre-Incubator (OGIPI). 
  link_label: More information
  link_url: https://www.businessoulu.com/tietoa-meista/ohjelmat-ja-hankkeet/oulu-game-industry-pre-incubator/
  stage: just-exploring, getting-started
- title: Bisnesmajakka / Business Lighthouse
  description: OSAO Bisnesmajakka/Business Lighthouse is an inspiring, easy to land pre-incubator on the OSAO Kotkantie campus for those interested in entrepreneurhip. 
  link_label: More information
  link_url: https://www.osao.fi/opiskelen-osaossa/opiskelu/osao-bisnesmajakka/
  stage: just-exploring, getting-started
- title: FIBAN
  description: Finnish Business Angels Network
  link_label: More information
  link_url: https://fiban.org/
  stage: ready-to-grow
- title: Technopolis
  description: Technopolis offers office spaces for startups in different parts of Oulu.
  link_label: More information
  link_url: https://technopolisglobal.com/fi/?gad_source=1&gbraid=0AAAAABpQzOrgK2fgbe7FOMPfWPhBjy5qk&gclid=EAIaIQobChMImr2OrL67jAMVvBBECB1gRRWZEAAYASAAEgIGifD_BwE
  stage: getting-started, ready-to-grow
- title: Butterfly Ventures
  description: Butterfly Ventures is the leading seed entry deep tech VC in the Nordics.
  link_label: More information
  link_url: https://butterfly.vc/about-us/
  stage: ready-to-grow
- title: Nordic Option
  description: Nordic Option is a venture capital fund focusing on and investing in growth phase companies in Northern Finland.
  link_label: More information
  link_url: https://nordicoption.fi/
  stage: ready-to-grow
- title: Korpunsiemen
  description: Korpun Siemen’s first investment in the target company is 50.000-100.000€ and it can make further investments in subsequent rounds up to a total investment of 200.000€.
  link_label: More information
  link_url: https://www.korpunsiemen.fi/en/
  stage: ready-to-grow
- title: FabLab
  description: FabLab’s high technology is available to all, free of charge. At BusinessAsema FabLab, you can learn, use and utilise modern digital methods of manufacturing in innovation, application and showcasing your expertise.
  link_label: More information
  link_url: https://businessasema.com/en/fablab/
  stage: just-exploring, getting-started, ready-to-grow
- title: StartupOulu's mentoring sessions
  description: Get mentoring from experienced startup experts! We offer walk-in mentoring for your business case every Wednesday from 9:30–11:30 at the Business Corner (Yliopistokatu 9, Linnanmaa campus), and every Thursday from 9:30–11:30 at BusinessAsema (Uusikatu 52). You can also book mentoring sessions at other times with StartupOulu’s Development Manager, Ilkka Immonen, by clicking "More information" below.
  link_label: More information
  link_url: https://outlook.office.com/bookwithme/user/8f2d5301926347ceb3875850dcae5dac@oamk.fi/meetingtype/6CyXbjj1eECPRhYTHWxASA2?anonymous&ep=mcard
  stage: just-exploring, getting-started, ready-to-grow
